### ISSUE TITLE
Wonderful 8 fonts but the installing procedure shows at the end only two fonts

### ISSUE THREAD

**Issue by Zugchaser** [tchristopherwhite/Dihjauti#1]
All fonts were installed the result is 2 fonts as a family each with 4 fonts. The files are correct in the windows/fonts Only the two shown als family are visible in word etc. The option i have sometimes that the bold or italic fonts is working, when i use the basic family and then the function bold. But here no changes applied.
In Win 11 the developer uses the optional feature of other language package in combination to show then the fonts. Everything i tried to use this 8 wonderful fonts, but win 11 is probably the key to find the solution. Any ideas?thx M.

**Comment by Zugchaser** [comment]
It works perfect in the Program Affinity Publisher. For office users it should be an Installtion without linking a fonts family. Thx.

**Comment by tchristopherwhite** [comment]
I'm not certain about the issue? Dihjauti comprises two typefaces: the
regular version, plus the Scotch version, which has different styled Qs.
They both have Regular, Bold, Italic, and Bold-Italic. A font is literally
one version of a typeface; that is, Regular, or Italic, et cetera. Dihjauti
is technically one typeface with four fonts, and there are two versions
with differing Qs. Does that help?

**Comment by Zugchaser** [comment]
Thx for your answer. in the  production process of a book the author use a textprogramm here MS Word. There are the two fontsfamily visible an the text is changing with the Buttons Bold or  Italic or both. Then the Text is places in a desktop publishing program (e.g. Affintiy publisher or indesign) then the two fonts families and the subcatories as a single font is visible. The Regular and the bold dihjauti is correct translated or stylelinked, the italic not. That means a text in dihjauti italic or dihjauti S must be formated a second time. I tested it meanwhile on two platforms win10, win11 with four devices….the result is always the same. But anyway the font is outstanding! With both different Q!

**Comment by tchristopherwhite** [comment]
Interesting. I'm, unfortunately, not all that familiar with Windows, as I
only use Macintosh. I'll look into the italic issue—I may have named them
incorrectly, but I do not think that I did? And, thank you. I always like
feedback, and appreciate the compliment. I've been working on this typeface
for years, until it finally decided what it wanted to be. :) I mainly
created this for my book series that I'm still working on, plus my interest
in linguistics, because so few typefaces support African and First Nation
languages. I think that the issue has to do with the respective word
processing programs, as has come up in numerous discussions with SIL.
Anyway, thanks again.

**Comment by tchristopherwhite** [comment]
I just updated the fonts. so maybe they'll work now?

**Comment by Zugchaser** [comment]
Thx, dear Christopher, I tested on the Platform win10 win 11, with MS WORD AND Affinity Publisher Vers.2.53 everything is fine and the italic font is now correct shown in the desktop publishing program. That is great and again a wonderful font!

**Comment by tchristopherwhite** [comment]
Glad to hear it!
