### ISSUE TITLE
Thank you & feedback on two Coptic letters

### ISSUE THREAD

**Issue by Mina-H-Samy** [tchristopherwhite/Dihjauti#2]
Wow that is a beautiful font. The Coptic letters are so well done. I wanted to say thank you for your work and for sharing it for free!

Only feedback is: the Coptic ⲡ and ⲛ look too similar. I think it would be better if the ⲛ looked more like the ⲙ and that the ⲡ had square edges like the capital letter.

**Comment by tchristopherwhite** [comment]
Why, thank you. I had been working on this typeface for years before
deciding to add Coptic, as I love Ancient Egyptian. I spent years working
on this design to incorporate it into the other scripts, including
referencing many stone and written manuscripts, plus my own influence in
how I would draw certain letters. I find many Coptic fonts odd. This leads
me to believe designers simply follow the base glyphs in Unicode (which a
number are incorrect) while designing them, instead of researching them.
Anyway, I am content with it now. :)

**Comment by Mina-H-Samy** [comment]
You're exactly right -- looking at a lot of Coptic fonts and Coptic manuscripts reveals how there are several ways in which they really differ. 

Would you be open to making slight adjustments to a couple of letters? I am using this font in an iOS app for Coptic liturgical texts and it can sometimes be difficult to read a phrase that has both ⲛ and ⲡ , for example: ⲫⲛⲁⲩ ⲙⲡⲓⲥⲙⲟⲩ (the time of incense). What do you think?

**Comment by tchristopherwhite** [comment]
I can easily do that. I just need your preference to design; the 'n' could
be done similar to the capital, like you show above. I had played around
with a design similar to that, which looked odd, but still works. However,
if I do an 'n' like that I would tend to round the right corner, as it is
now, but steeper. I would also jus email you the altered version. :)

**Comment by Mina-H-Samy** [comment]
That would be tremendous! Yes, let's go with your idea, I think that will look best with the other letters in the font.
Please send me a donate link as well -- I would like to buy you a coffee or two :)

**Comment by tchristopherwhite** [comment]
Okay. I realized that the current design "stuck" do to the others not
conforming; the design mirroring the capital fails in the italic.
Re-examining the glyph, I could also just remove the serif from the bottom
right, which in hindsight I probably should have done; i.e., like the
bottom of the capital (angled on the baseline). So, I tried a few
alternates, but they still look off compared to the rest of the lowercase.
Anyway, I'll draw some and send pics. As to a "donate" link. I do not know
how to do that—I'm an artist, not a programmer. :)

**Comment by Mina-H-Samy** [comment]
Looking forward to seeing what you come up with!
And, I can help you set up the donate button. Do you have Paypal? You can start here: https://www.paypal.com/donate/buttons

**Comment by tchristopherwhite** [comment]
Yes, I do have Paypal. So, these are two versions where the right serif has
been altered. The first is an alteration of the original. The second one
follows the curve of the 'o', like the 'm', which does work with the
design. I tried a version with the curve on the bottom, but that design
makes it look too similar to a 'u', which could also technically work?

**Comment by Mina-H-Samy** [comment]
It sounds like you attached photos, but I can't see any.
GitHub tells me you are responding by email, so I think that means attachments may not be automatically included.

**Comment by tchristopherwhite** [comment]
Here are some new designs.
<img width="690" alt="n 2" src="https://github.com/user-attachments/assets/82f9dfe0-36d3-4866-ac38-6ec09fc0d52c">
<img width="476" alt="n~" src="https://github.com/user-attachments/assets/c15b6b6a-cd4d-438e-87bd-1d6624c0465e">

**Comment by Mina-H-Samy** [comment]
Thank you for these!

I have an idea that might make it easier to resolve this: what do you think of leaving the ⲛ as is and modifying the ⲡ instead?
See this 14th c. manuscript for example (first line has ⲙ, second line has both ⲛ and ⲡ right next to each other)

<img width="290" alt="image" src="https://github.com/user-attachments/assets/6a5f5511-0b69-43c2-97fa-37826d2fb4a6">

the ⲙ ⲛ from your font are perfect -- very traditional. I think the curve on the ⲡ is what is making it hard to make out as a ⲡ -- as far as I have seen, it is always rendered with a straight edge on top.

Can the ⲡ simply be a smaller version of the capital Ⲡ?

Also, please send through your PayPal email, I can just do it directly I think :)

**Comment by tchristopherwhite** [comment]
Yeah, I like that idea better. How is this 'p"?
<img width="412" alt="p" src="https://github.com/user-attachments/assets/d503647a-a9c2-4821-ad5f-90326937d517">

I was thinking that the idea to add a link to Paypal would be nice. :)

**Comment by Mina-H-Samy** [comment]
That is perfect @tchristopherwhite! Yes definitely very distinctive and now easier to distinguish.

I can help you set up the link! Follow [this](https://www.paypal.com/donate/buttons) and create a button. There should be some option to embed the button in a website which will give you some HTML -- once we have that, we can follow [this](https://stackoverflow.com/questions/30915253/creating-a-paypal-donation-button-in-an-md-file) to replicate it on GitHub. When you have the HTML let me know and I'll guide you through the rest :)

**Comment by tchristopherwhite** [comment]
Nice. I'll actually redo the fonts with the new 'p', then upload them here. I know not a lot of people will use Coptic anyway—I have my typeface available on many sites, but this is the homepage. I also put a Paypal link on my page.

**Comment by Mina-H-Samy** [comment]
Looking forward to it! 

I found the PayPal link. It might be easier for people to see if you include it in the README as well.

**Comment by tchristopherwhite** [comment]
I have uploaded the new versions. I altered the the n's and p's to flow better with how they are written (as in the manuscript). The n's were off on the right leg, both regular and italic. Also, good idea about the Paypal link. On another note: does the Coptic work well in whatever programs you are using it in? I ask because a few people mentioned that the language code was wrong, but I researched it, and it is what it should be, so...?

**Comment by Mina-H-Samy** [comment]
It's looking fantastic, check it out:

<img width="201" alt="image" src="https://github.com/user-attachments/assets/4ee32fc1-00bf-493a-bb92-97aefc3ddf6b">

Thank you very much. Font is beautiful and your talent shows through -- you have a great eye for this.
Please let me know if the PayPal thing worked too. All the best!

**Comment by tchristopherwhite** [comment]
I agree, it looks great. And, you are welcome. It only took me three
iterations for it to become what it is now; it's a growing process. :)
Paypal worked, and thank you. Support works for me. So ... Are you a
student of Coptic? Do you speak it, or know it well? I have been trying to
incorporate more into a sci-fi series that I've been working on, where
ancient Kheimian is the primary Galactic tongue, which I call Irden
Las: *Esteemed
Tongue.* I was deciding on how best to transcribe the fricatives 'ch' and
'dzh', but using only two letters. I had originally thought of using ç/çh
for 'ts/tsh' (Ch for English) and x/xh for dz/dzh (J for English). Ideas?

—T. Christopher

**Comment by Mina-H-Samy** [comment]
I do know Coptic, but I'm not entirely sure what you mean -- you want to transcribe Coptic fricatives to English? What Coptic letters are they?

**Comment by tchristopherwhite** [comment]
Yes, to transcribing them. So, the letters are not Coptic but from the
Galactic Alphabet, what the Native Americans refer to as the language of
the Star Beings, which include the dolphins and whales. But the Coptic
equivalents would be Shima and Gangia, thus why I was thinking of using ç
and x. Originally I transcribed them as ts/dz, respectively, and tsh/dzh. I
wanted to simplify the sounds as digraphs, because that is how they are
written in the Galactic Alphabet.

**Comment by tchristopherwhite** [comment]
If you would like to see the alphabet, you can look it up under its name:
Zeshit. I can also send you a copy as well? Anyway, all the digraphs in
this alphabet use a base glyph + h, so ... ç/çh, s/sh, z/zh, d/dh, t/th,
k/kh, h/hh, x/xh, g/gh, et cetera. In this alphabet typical kh=q (back of
the throat), while hh=the rasping guttural h. Does that help? I could also
use Ezh for dz/dzh?

**Comment by Mina-H-Samy** [comment]
I do like ç I would go with that I think. Good luck with it!

**Comment by tchristopherwhite** [comment]
It's simple, and a lot of languages use ç for 'ts' anyway, which is why I
liked it. Plus, X already resembles gangia as well. Anyway, I have
transliterated these names from my Egyptian dictionary, and would like to
know if they are somewhat accurate? Granted, the accuracy is based on how I
remember the language from past lives. I have had issues trying to figure
out certain vowel pronunciations, such as ou, versus oou. Is there a
glottal stop differentiating them? Plus: All my transliterations from the
akashic library translate ḥ as hj (hy in English). An example would be
*heart* and *mind*: hjeit and hjet. So ... below are some examples of
characters and place names. Do I have them somewhat accurate? I refer to
the fires (energies) as asher, is that correct? Also, is the word for fire,
as in physical fire, qerōm/kherōm?

*Avai Rr**e**iri* /'a:.vai 'hrei.ri:/, *Courageous Flower*

*Dz**hid Hjowu* /dži:d 'hjo.wu:/, *Radiant Rain* —this could also be Xhid
Hjowu

*Dz**hora Waa* /džo.ra 'wa:-a/, *Mighty One* —this could also be Xhora Waa

*Fajii* /fa:.'ji:-i/, *Topaz* (pale blue)

*His-heis* /hi:s.'heis/, *Heartfire* —a translation of one of the fires
(energies) in my series, of which there are thirteen. And yes, I found
specifically thirteen words associated with fire, which I recalled later
were the names of the chakric energies used to manipulate reality; that is,
hjeka (magic).

*Hemhemut* /hem.'hem.u:t/, *Peals‐of‐thunder*

*Is-hjeirit* /i:s.'hyei.ri:t/, *Breath-of-Heaven*

*Ro**kh**ehat**a* /ro.k’e.'ha:.ta/, *To‐burn‐beyond*

*Aasheps R**ijaa* /'a:-a.šeps ri:.'ja:-a/, *Sacred Sun*

*Ati Hjais* /*'*a.ti: hjais/, *Sovereign Song*

*J**ah Hit* /'ya:h hi:t/, *Moon Temple*

*Dz**heseri* /*'*dže.se.ri:/, *Glory;* she is a child of throatfire.

*Ijam* /*'*i:.ja:m/, *Sea;* he is a child of mindfire.

*Imii** /i:.**'m**i:-i/,* *Flare;* she is a child of spiritfire.

*Kh**a**tarta* /qa.'ta:r.ta/ *Incense;* he is a child of crownfire.

*Kh**enu Rijaa* /qe.nu:.ri:.'ja:-a/, *Brave Sun;* he is a child of
sacralfire.

*? Lei**'**ikusa* /leh·*'*ih·ksa/, Lihhaku’s sister.

*? Li**h**h**aku* /lih·*'**h’*ah·kuh/, a Hand, Lei’iksa’s brother, Ni'iha’s
closeness.

*? Ni**'**iha* /nih·*'ih*·ha/, a Hand, Lihhakuz’s closeness.

*Mehet* /'me.het/, *Granite *(a reddish variety); he is a child of
heartfire.

*Siju* /*'*si:.ju:/, *Star;* she is a child of starfire.

*Tserem* /*'*tse.rem/, *Surge;* he is a child of solarfire. —could also be
Çerem

*Hjerep em Sethesu* /'hje.rep em se.'þe.su:/, *Chief of
Those-who-lift-up-praises*

*Hjoru* /'hjo.ru:/, *Sky*

*Ijahhu Sh**aa* /i.'ja:.h’u: 'ša:-a/, *Splendid Garden *—my name for Gaia,
which was orignaly a living library

*Ijawo em Peheti* /i.'ja:.wo em pe.'he.ti:/, *Flame of Valour*

*Mei* /'mei/, *Love*

*Paahhi* /'pa:-a.h’i:/, *To-be-joy*

*Shaa em Ba**ll**a* /ša: em 'ba:.þla /, *Garden of Sunrise*

*Tau-tehjen **Dz**heser* /tau 'te.hjen 'dže.ser/, *Fiery‐scintillating
Glory* —could also be Xheser

*Eiri Hjei**dz**hut* /'ei.ri: 'hjei.džu:t/, *Beget Brilliance* —could also
be Hjeixhut

*K**au **U**ri* /kau 'u:.ri:/, *Sust**e**n**tative* *Mass of **Water*

Anyway, let me know...
Sincerely, T. Christopher
